SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS LCRO_SYNC_LOG;
DROP TABLE IF EXISTS NOTIFICATION_LOG;
DROP TABLE IF EXISTS DOCUMENT_REQUEST;
DROP TABLE IF EXISTS PSA_STAFF;
DROP TABLE IF EXISTS CITIZEN;
DROP TABLE IF EXISTS REGISTRY_OFFICE;
SET FOREIGN_KEY_CHECKS = 1;